name: lunar_calendar
description: Lunar calendar library for Dart Native
version: 1.0.0
homepage: https://novousoft.com/

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
